version: '3.8'

services:
  tcf-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tcf-backend-dev
    network_mode: "host"
    environment:
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://admin_tcf_canada_STZ:admin_tcf_canada_STZ@localhost:3306/admin_tcf_canada_STZ
      - SECRET_KEY=dev-secret-key-change-in-production
      - STRIPE_MODE=test
      - STRIPE_TEST_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
      - STRIPE_TEST_WEBHOOK_SECRET=${STRIPE_TEST_WEBHOOK_SECRET}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - EDGE_TTS_PROXY=${EDGE_TTS_PROXY}
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./audio_responses:/app/audio_responses
      - .:/app  # hot-reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["sh", "-c", "python init_db.py && flask run --host=0.0.0.0 --port=5001 --reload"]